### ISSUE TITLE
Somfy Motion Sensor not working

### ISSUE THREAD

**Issue by iRonin** [dubocr/homebridge-tahoma#14]
I've got issue with Somfy Motion Sensor - it got detected, I can see it in the Home app, I think it was correctly working at the beginning but as soon as I created an automation it keeps saying Triggered. The sensor works fine in Somfy. I've been thinkering with homebridge for only couple of days but could help debugging with some guidance (I'm short on time for this sort of things).

**Comment by dubocr** [comment]
TaHoma events like motion events can't be pushed to any application that's why the motion state not alway represent the true state.
If you want to force a periodic refresh (not done by default as it overload TaHoma servers), you can try to replace the content of overkiz-api.js in the plugin folder by the content of this one 
[overkiz-api.txt](https://github.com/dubocr/homebridge-tahoma/files/1405058/overkiz-api.txt)
and updated the plugin config file by adding 
```
"alwaysPoll": true,
"pollingPeriod" : 10,
```

e.g.
```
{
        "platform": "Tahoma",
        "name": "Tahoma",
        "user": "XXX",
        "password": "XXX",
        "alwaysPoll": true,
        "pollingPeriod" : 10
 },
```
 
This will normally update the motion sensor state in Home within 10 seconds

**Comment by dubocr** [comment]
TaHoma events like motion events can't be pushed to any application that's why the motion state not alway represent the true state.
