### ISSUE TITLE
Certificate has expirated

### ISSUE THREAD

**Issue by thomtomdup** [dubocr/homebridge-tahoma#177]
Hello.
Since yesterday I have an error « certificate has expirated » in my log file.
I have updated all packages but nothing solved this problem.
Now in my home app all device not detected.
Do you have process to solve it ?
Thank you very much for your help.
Best regards.
Tom

**Comment by jerem916** [comment]
Hello ! I Have the same problem here !

**Comment by showbizzi** [comment]
Hey there,
I have the Same issue since yesterday. 

Br 
Showbizzi

**Comment by henryblackman** [comment]
Same here.  I can't find a reference to a certificate in the code, and when connecting to the API URLs manually the certificate hasn't expired.  I'm at my limit here though - not being a HomeKit developer.  Will continue to look and try to debug.

**Comment by mman** [comment]
Please post a more detailed log message. On Saturday on of the intermediate certificates from user trust CA expired and that caught many unprepared. In my case on an unrelated project connections started failing because I had the expired intermediate certificate present in the chain. Ubuntu removed that same certificate via security update on Monday. So you need to dig where is this coming from and check the whole chain.

**Comment by thomtomdup** [comment]
I don't have more details.
My config is simple : Raspberry Pi 3 + NodeJs + PM2 + HomeBridge + HomeBridge Tahoma.
In the log file i have the certificate error message and an error connection to my account after.
This process was working perfectly durring 1,5 years and since saturday 4.45PM in France, the system is down.

**Comment by mman** [comment]
Here is the background of what happened: https://access.redhat.com/articles/5117881.

In your case you need to find out which URL you are hitting and which is failing. One of the endpoints something on your RPI is hitting is most likely serving expired cert.

I have ``homebridge`` + ``homebridge-tahoma`` like this:

```
# npm -g list|grep home
├─┬ homebridge@0.4.53
├─┬ homebridge-hue@0.11.62
│ ├─┬ homebridge-lib@4.5.7
├─┬ homebridge-tahoma@0.3.33```

```
$ cat /etc/issue
Raspbian GNU/Linux 10 \n \l
```

and it works well.

**Comment by MrClou1A** [comment]
same issue on my side side 2 days... anything I can do by myself?

**Comment by mman** [comment]
@MrClou1A Please post a detailed log message that you are seeing, I will try to help.

**Comment by showbizzi** [comment]
I tried the Plugin on my second RPI with raspian buster and hoobs3. It worked. 
So this is my Workaround because an update on the Other RPI with raspian Stretch  had no impact on the certificate issue -.-

**Comment by intermittent-user** [comment]
I have the same problem, homebridge has been running fine for a long time, but just stopped a few days ago. It's getting stuck trying to log into TaHoma Server 

Fetch accessories...
Login TaHoma server...
Unable to login: Error: certificate has expired

I've this setup :

pi@raspberrypi:/ $ cat /etc/issue
Raspbian GNU/Linux 8 \n \l

pi@raspberrypi:/ $ npm -g list|grep home
├─┬ homebridge@0.4.28
├─┬ homebridge-lightwaverf@0.1.0
├─┬ homebridge-tahoma@0.3.30
│ │ ├── os-homedir@1.0.2

pi@raspberrypi:/ $ node -v
v6.9.2
pi@raspberrypi:/ $ npm -v
6.14.5

I did try "npm install -g node", but it failed on "node installArchSpecificPackage", which reminded me I'm on an old node because my Raspberry Pi is ArmV6.

Any suggestions what to try next ?

**Comment by thomtomdup** [comment]
Hello.
I couldn’t wait more time for solving the problem, I have delete and install new version of raspberry pi os and homebridge.
All works now.
Thank you for your support.
Regards.
