### ISSUE TITLE
iO Motors and Enocean temperature sensor

### ISSUE THREAD

**Issue by URBANsUNITED** [dubocr/homebridge-tahoma#18]
Hi!

Thanks for this great plugin. 
But I have serveral issues

1. With Somfy iO motors you are able to set the heights in percent. Means I can say open 15% for example.
That works not proper. Homekit jumps between the heights so I can't drive my 15%. Maybe 5% or 2%. But the height sets to 85% 
Full open or full close works perfect

2. I can't combine the iO motors into the automatic scenes. Homekit complains I have to update my Homekit hub to make it work.
Problem is that my homebridge hub is up to date.

3. The attached enocean temperture sensor is visible, but greyd out and spitts out 0° instead of the real temperature as seen in my Tahoma interface

Is there any way to make my 3 points work? Where can I give support? What do you need from me?

Many thanks in advance

URBANsUNITED

**Comment by dubocr** [comment]
Hi,

Firstly can you reproduce the issue with your shutter then log with your tahoma credentials here : http://home.dubocr.fr/tools/setup.
Once that done, I will have a look to understand your issue.

Thanks

**Comment by URBANsUNITED** [comment]
Done!
But lots of actions missing as I can see from the log file. 
I closed Maditas window just for the record
Maybe a video will help to see the % jumping and behavior of the shutters?

**Comment by URBANsUNITED** [comment]
And the Enocean temp sensor is showing correct value within the log, but HomeKit say 0° as shpown on the attached pic.
![img_e9db88aa3f78-1](https://user-images.githubusercontent.com/6212300/34070483-699a9f88-e267-11e7-9d0f-a2b9d5f56fcd.jpeg)

**Comment by dubocr** [comment]
For the temperature, you car replace the "TemperatureSensor.js" file located in the 'accessories' repository by this one : [TemperatureSensor.js.zip](https://github.com/dubocr/homebridge-tahoma/files/1564961/TemperatureSensor.js.zip). Some device reports their temperature in °K, other in °C.

For your shutter, the history logs lets me think you don't 'say' a percentage but 'select' it with the slider. Isn't it ? So yesterday at 13:39:19 (last action) what did you try to do and what's wrong for you (yes a video could help to explain your issue) ? Logs show a command at 79% and another at 88%. This behavior could be the consequence of a little stop on one position when sliding. Can you give me your iOS version ?

Do you have an Apple TV or an iPad. Because if Homekit requests you to update your Homekit hub it refers to one of these devices.

**Comment by URBANsUNITED** [comment]
Good news!

The temperature sensor works now after your update. Thanks Would it be possible to get one position after decimal point? In the Tahoma is also no position after decimal point atm. 

The roller motor has been operated manualy to set it in its position. That's the advantage of iO to name the height you wish to set.
But that's currently impossible. You pull the "switch" in homekit to a level, it operates, but doesn't act as you wished. Sometimes it starts and stops directly, if you'll increase the drop, it drives the shutters, but not to the wished posistion.
It's difficult to explain. Maybe you want a video which shows my operation and how the blind acts? I could do this with the help of my wife. No problem.
Just for the record: Tap to open or tap to close works without any issues.

Btw. I am using an iPhone 7 with IOS 11.2.1 and an Apple TV 3 with its latest firmware 7.2.2 which is based on IOS 8.3 as far as I know. Maybe this is the reason for the setting scenes and automatics for the roller shutters issue.
I could try to set my iPad on the latest firmware as the control center and try to see how it acts then. But I wanted to control my Homekit setup without an iPad as it is not always in house to keep the automatics runnings. That's the reason for the ATV3. 
ATV3 which is basically enough as I don't and will not use any cameras...

Thanks

URBANsUNITED

**Comment by dubocr** [comment]
Hi,

Can you try to control your shutter with Siri (by asking "open [SHUTTER NAME] at 20%") and tell me if, for you, the behavior is good.
