### ISSUE TITLE
[Event Listener] Error 400 - No Registered Event Listener after session timeout

### ISSUE THREAD

**Issue by thehilsnz** [dubocr/homebridge-tahoma#334]
Hi,

The plug-in was working fine, but now it's throwing a "Error 400 - No registered event listener [UNSPECIFIED ERROR]".

You can see from the screenshot that it worked fine one minute, then failed the next. It seems to work the first time after a restart, then fails. I tried to follow along with the an earlier issue but as most of it was in French it was a little tricky - I got the impression this would be solved in an upcoming release, but I'm not sure if that is that case, or that release is still pending. I initially had a polling period of 600, then I tried 300 as per the other thread, but have now reverted to 30, and the issue arises across all of them.

I've also pasted my (redacted) config in case that helps.

        {
            "name": "Connexoon",
            "service": "connexoon_rts",
            "user": "[redacted]",
            "password": "[redacted]",
            "pollingPeriod": 30,
            "_bridge": {
                "username": "[redacted]",
                "port": [redacted]
            },
            "platform": "Tahoma"
        },

Thanks in advance for your help.
Hilary

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/70087748/136312725-4afd4912-47da-497e-96f9-2df83e74cbcf.png">

**Comment by Rammelkast** [comment]
Noticed the same issue as well lately.
![image](https://user-images.githubusercontent.com/12514032/137616260-9f0ba3bd-fd59-42ed-84cd-4e6a2fdb53c6.png)

**Comment by ludoblockdevice** [comment]
same here since few weeks.

**Comment by denbrian** [comment]
same

**Comment by ludoblockdevice** [comment]
still same issue, it logs an error every 20 minutes, what the plugin tries to do each 20 minutes ?

**Comment by dubocr** [comment]
Hi,

This seem to come from the server session timeout that seem to be shorter than a minute. But as @thehilsnz says, even at 30 sec the issue persists. (the unmasked value of listener id can confirm that, if the value before and after login is the same)
Release 2.2.27 improve fetcher registration in case after the session timeout (error 401) to avoid the bad listener id (error 400) by registering a new listener.

But this won't solve the fact that listeners are useless because session has expired each time the listener fetch for events.

I'm interested in any log after plugin update.

@phimage it's not necessary to hide listener id as it is only valid inside your session. No-one else can use it and it is (unfortunately in this case) invalidated at any new session (after each login). If you want, you can hide part of it to let us know which one is used in each requests.
