### ISSUE TITLE
[PositionableRollerShutterUno] Illegal core:ClosureState value

### ISSUE THREAD

**Issue by Stonie70** [dubocr/homebridge-tahoma#341]
Hy,

I always get the following warnings in the Hombridge Protkoll:

[11/7/2021, 5:13:45 PM] [homebridge-tahoma] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number -24 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[11/7/2021, 5:13:45 PM] [homebridge-tahoma] This plugin generated a warning from the characteristic 'Current Position': characteristic was supplied illegal value: number -24 exceeded minimum of 0. See https://git.io/JtMGR for more info.

Please can you help me ?

Thank you very much.

**Comment by dubocr** [comment]
Hi,

This issue is generated because your device as invalid position value. What kind of device it is ?
As this message is a warning, you should simply ignore it.

**Comment by blmyr** [comment]
Hi @dubocr. I had been using the plugin in the past and it worked great most of the time. Some time ago (couple of months) my bridge started shutting down randomly (or not, dunno). I didn't figure out if it was because of Tahoma or some other plugin. I took some time and set the bridge up again. I only added and configured your Tahoma plugin for now.

I am having the same problem described here. Same warning in the logs. It only shows up for all PositionableRollerShutterUno devices. The PositionableRollerShutter devices work fine and don't show errors or warnings.
Now I can use HomeKit to open, close and position the roller shutters but as long as they are not closed all the way the PositionableRollerShutterUno devices always show an ongoing „will be opened“ status. Even if they are fully opened they show this status. This is something I have never experienced in the past with your plugin. Do you have any solution?

Thanks,
Daniel

**Comment by blmyr** [comment]
I recorded the following values for the states. I guess the core:ClosureState 124 is causing the problem.

**opened**
core:ClosureState 124
core:TargetClosureState 0

**50% opened**
core:ClosureState 124
core:TargetClosureState 50

**closed**
core:ClosureState 124
core:TargetClosureState 100

**Comment by dubocr** [comment]
Hi,

Do you always encounter this issue ? It might be an issue on tahoma release which could be now fixed ?
@blmyr I see in your last config that all the `core:ClosureState` have the value 0

**Comment by iMicknl** [comment]
@dubocr for the PositionableRollerShutterUno, I don't think you can rely on the position. We have seen similar issues where the position is below 0 or over 100.

**Comment by dubocr** [comment]
> @dubocr for the PositionableRollerShutterUno, I don't think you can rely on the position. We have seen similar issues where the position is below 0 or over 100.

Thanks @iMicknl, do you know if another state have trusted value ?

**Comment by iMicknl** [comment]
What I recall is that TargetClosure is the one to go, since current position cannot be trusted at Uno devices. In theory the device is stateless, where Somfy TaHoma back-end is keeping the latest state they know. What I understood from Somfy is that Uno are devices that allow wired devices to be transformed into wireless one.

**Comment by dubocr** [comment]
Thank you, I don't know why they add the state as it isn't accurate. Very strange and the value 124 must have a meaning.
I'll only take target into account for the moment.

Thks

**Comment by Teclini** [comment]
#372 solved thx

**Comment by Vogelschutzwarte** [comment]
@dubocr Thank you very much for your support, RollerShutterUno is also my device - status perfectly working again in homekit

**Comment by blmyr** [comment]
@dubocr since the issue was present the Tahoma updates did not change the behavior. After updating my homebridge and the plugin to the latest version it works again. Thank you.
