### ISSUE TITLE
This plugin generated a warning from the characteristic 'Target Position'

### ISSUE THREAD

**Issue by maschbaer** [dubocr/homebridge-tahoma#348]
Since some updates of the Tahoma Box firmware, I noticed that from time to time the HK lost the connection to the Tahoma Box. After a restart of the HA everything worked fine again. Today, this happened again and I found the following in the log:

`Awning > PositionableHorizontalAwningUno
[2021-12-25 17:13:06] [homebridge-tahoma] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number 124 exceeded maximum of 100. See https://git.io/JtMGR for more info.`

The quoted link says that such errors shall be reported to the plugin developers.

regards,
Jan

**Comment by maschbaer** [comment]
![3542AA12-3119-401A-8A25-906ECD6E051D](https://user-images.githubusercontent.com/56022085/147394079-70838695-8b49-4d0c-bf65-2e625561e31b.jpeg)

bridge last 4 digits: 7200

**Comment by dubocr** [comment]
Hi,

This issue is generated because your device as invalid position value (124 as position should be between 0 and 100).
Is your state "core:TargetClosureState" evolve when you change your awning position ? (to check, change the position then log in again to the page to check the state value).

As this message is a warning, you should simply ignore it.

**Comment by dubocr** [comment]
Please follow #341
