### ISSUE TITLE
Tahoma enable to loggin : Error:

### ISSUE THREAD

**Issue by Jer3m** [dubocr/homebridge-tahoma#58]
Bonjour Romain,

Je tourne sur un _raspberry pi b3+_ sous _Raspbian lite_.

Après avoir suivi le tutoriel, je démarre _homebridge_ manuellement avec le plugin _homebridge-Tahoma_ installé et configuré, la connection se fait, ça fonctionne, parfait.

![capture d ecran 2019-01-06 a 12 55 45](https://user-images.githubusercontent.com/46055914/50735942-7966a180-11b6-11e9-8ded-cfcb771aaaed.png)

Au passage merci beaucoup pour cette réalisation vraiment pratique et indispensable.

Je fais les manipulations qu'il faut pour obtenir le lancement de homebridge au démarrage du système avec _systemd_, je fais un sudo reboot, mais _homebridge_ ne se lance pas.
Voici le log que j'obtiens

![capture d ecran 2019-01-06 a 13 27 13](https://user-images.githubusercontent.com/46055914/50735971-db270b80-11b6-11e9-87c9-c57367d233b8.png)

J'essaye d'aller me logger sur le site de Tahoma et sur l'appli, impossible.
Sur la page web j'ai le message "too many request, try later"
Sur l'appli, problème de mot de passe ou de compte d'utilisateur (qui sont pourtant les bons)

Si j'enlève les informations _Tahoma_ dans le _config.json_, alors _homebridge_ démarre bien au boot.

Y aurait-il une solution pour résoudre ce problème?
Si tu as besoins de testeurs ça serait avec plaisir.

Par avance merci.

Jérémie

**Comment by reg10** [comment]
Hey there,

I have the Same problem.
I have the Connexoon rts registerd but i saw iT wasn’t on the tahomalink.com
So when i try to connect iT fails. Because im not on the tahomalink.com
I’m on the somfy.nl

Is the Any way to fix this because the service is different the de Normal connexoon IO.
Of is there a way to connect to tahomalink.com with the connexoon rts?

Thanks for helping

**Comment by reg10** [comment]
Hi Jer3m,

This didn't work for me.

I think that my problem is more regarding the different device I use. by Somfy you have the Tahoma for IO and RTS, the Connexoon IO and the Connexoon RTS. I don't know for sure but when I activated the Connexoon RTS it signed me up at https://www.somfy.nl/mijn-gegevens/mijn-huisautomatisering-box?abo_id=<some numbers and letters>

When I change the service in the config.json to Connexoon it still want to sign me up at tahomalink.com. problem is that I don't have a account there because the Connexoon RTS doesn't go there.

this is the message I receive. regarding changing the config. and adding a server called Connexoon RTS and directed it to Somfy.nl/inloggen. I went back after imputes form Jer3m and tried it again.

<img width="788" alt="schermafbeelding 2019-01-13 om 14 06 17" src="https://user-images.githubusercontent.com/46611529/51085623-69157000-173c-11e9-9c95-dfa5e7f945d7.png">

maybe @dubocr can help.

**Comment by dubocr** [comment]
Hi reg10,

Can you try to log there with your Somfy credentials : https://home.duboc.pro/tools/setup ?

Thanks.

**Comment by dubocr** [comment]
Sem you succeed yesterday. So TaHoma server is good. Can you both give me your node JS version
`node -v`

**Comment by Jer3m** [comment]
Salut Romain,

I am running the v10.15.0 node version.

I've succeed but with the first attempt.
I've reinstalled the plugin and I've changed the overkill-api.js, HeatingSystem.js, Humidity.js and Light.js.
The second solution didn't work for me:
Voici les fichiers. Fan.js et Light.js dans accessories et index.js à la racine.
Fan.zip
Light.zip
index.zip

Ensuite il faudra ajouter la configuration suivante :
"forceType" : { "Ventilateur" : "Fan" }

En espérant que ça fonctionne du 1er coup.

**Comment by dubocr** [comment]
Salut Jerem,

Es-tu toujours avec la configuration refreshPeriod à 1800 ou 3600 ?

**Comment by Jer3m** [comment]
Je ne pense pas puisque je suis reparti sur un plugin de “base”, je n’ai pas touché au fichier config de homebridge.

Jérémie

**Comment by reg10** [comment]
Romain,

I can login and see all the devices, scenes and history.
<img width="1250" alt="schermafbeelding 2019-01-14 om 11 59 54" src="https://user-images.githubusercontent.com/46611529/51108932-ed76fa00-17f3-11e9-9373-db81b1bf0cc1.png">

<img width="1331" alt="schermafbeelding 2019-01-14 om 11 59 05" src="https://user-images.githubusercontent.com/46611529/51108895-d3d5b280-17f3-11e9-8c7a-2daabaddc3da.png">

so that works

**Comment by dubocr** [comment]
Mettre à jour le plugin et passer le paramètre "refreshPeriod" à 3600.

**Comment by reg10** [comment]
Romain,

Still my problem with the login is not solved

**Comment by dubocr** [comment]
Hi reg10,

Stop homebridge for 1h and any other third party client using TaHoma, update homebridge-tahoma plugin then restart homebridge.

**Comment by reg10** [comment]
I Will try iT tonight but i stil can’t login right now at The tahomalink.com

**Comment by Jer3m** [comment]
Hi reg10

You should stop reaching tahomalink, somfy app and your somfy account for a while.
When you try to reach one of them, you keep stocking server.

**Comment by reg10** [comment]
Alright. I Will try iT. Any idea for how long? No connection

**Comment by Jer3m** [comment]
First time i get this issue it took a while.
To be sure, wait until tonight, 3-4 hours at least.

**Comment by reg10** [comment]
Alright my homebridge is switch off, also apps and accounts are closed
only my Connexoon RTS is still active.

Do I need tot disconnect this one aswell?

**Comment by dubocr** [comment]
No, keep your bridge up

**Comment by reg10** [comment]
Oke,

for the complete resume. I log out all the apps and website interfaces. I leave the homebridge with new update Tahoma plugin running. and I leave the Connexoon RTS running.

after a while couple of hours I restart the homebridge with new config (including the login and password) or do I just need to reload the config somehow? so that the bridge keeps running and only the new config loads.

Please confirm

**Comment by dubocr** [comment]
You stop completely homebridge
You updade config.json file to add  "refreshPeriod" : 3600
You wait couple of hours
You start homebridge

For me bridge = Connexoon and it could keeps running.

**Comment by reg10** [comment]
afteer houres  testing still the following

[1/17/2019, 7:48:07 PM] [Connexoon RTS] Unable to login: Error: getaddrinfo EAI_AGAIN tahomalink.com tahomalink.com:443                     
[1/17/2019, 7:48:07 PM] [Connexoon RTS] { Error: getaddrinfo EAI_AGAIN tahomalink.com tahomalink.com:443                                    
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)                                                                           
  errno: 'EAI_AGAIN',                                                                                                                       
  code: 'EAI_AGAIN',                                                                                                                        
  syscall: 'getaddrinfo',                                                                                                                   
  hostname: 'tahomalink.com',                                                                                                               
  host: 'tahomalink.com',                                                                                                                   
  port: 443 }   

any thoughts?

**Comment by flexsense** [comment]
Can you change the service to Cozytouch in config file : 
`"service": "Cozytouch"`
Then restart homebridge
And send me error logs.

Thanks

**Comment by dubocr** [comment]
Can you change the service to Cozytouch in config file : 
`"service": "Cozytouch"`
Then restart homebridge
And send me error logs.

Thanks

**Comment by reg10** [comment]
Romain.

I changed the setting and this was the following result.

<img width="1022" alt="schermafbeelding 2019-01-18 om 12 12 06" src="https://user-images.githubusercontent.com/46611529/51383651-532bf480-1b1a-11e9-8666-66186650c958.png">
<img width="959" alt="schermafbeelding 2019-01-18 om 12 11 49" src="https://user-images.githubusercontent.com/46611529/51383655-558e4e80-1b1a-11e9-8a74-5760980245e3.png">

on the end it shutdown the homebridge server

config as following

{
    "bridge": {
        "name": "Homebridge-test03",
        "username": "CC:22:3D:E3:CE:53",
        "port": 40814,
        "pin": "031-45-053"
    },
    "description": "This is for Apple Homekit.",
    "accessories": [],
    "platforms": [
          {
            "platform": "Tahoma",
            "name": "Connexoon RTS",
            "user": "my e-mail adress",
            "password": "my paswoord for login at Somfy.nl/inlogggen",
            "service": "Cozytouch",
            "refreshPeriod": 3600
          }
    ]
}

**Comment by dubocr** [comment]
Hi Reg10,

I published a new plugin version, can you try to update. This version will retry 3 times when DNS resolution fails. I hope it will help to fix your network issue at startup.
You can rollback you parameters with Conexoon service.

**Comment by reg10** [comment]
Marvelous I works like a charm,
i will know check how it works and check if I can change some settings regarding the state off open/ closed/my position  normally 100% is down but can I change it to say 90% is the max down for me?
any guide lines?

anyhow much thanks for helping so far.  merci bien

**Comment by fafoulon** [comment]
Hi,

just to add my 2 cents, you should maybe make it by default to 3600 secondes when there is no parameter in the config file. Because I updated recently the plugin, and had some login failed errors. I had to search here to find the reason (too fast refresh).

Keep up the good work 😀

**Comment by dubocr** [comment]
Hi Tim,

Can you log there : https://home.duboc.pro/tools/setup
And tel me if succeed.

Thks,
